CREATE TABLE IF NOT EXISTS exp (
	UserID integer PRIMARY KEY,
	XP integer DEFAULT 0,
	Level integer DEFAULT 0,
	XPLock text DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	name TEXT,
	discriminator INTEGER,
	JoinDate INTEGER
);


CREATE TABLE IF NOT EXISTS economy (
	UserID INTEGER PRIMARY KEY,
	Balance INTEGER DEFAULT 0,
	UserName text
);